version: "3.9"

services:
  dummy-service:
    image: dummy-service:latest
    build:
      context: .                  
    ports:
      - "8000:8000"               
    restart: unless-stopped       